### ISSUE TITLE
Add "for ... loop" statement support

### ISSUE THREAD

**Issue by joseconstela** [joseconstela/webparsy#23]
This will allow users to scrape a list of urls (for example from a list of links) and perform sub-sequent scraping in those urls.

A random example / concept:

```yml
version: 1
jobs:
    steps:
      - goTo: https://myshop.example.com
      - listUrls:
          selector: '.items a.item'
          as: urlToScrape
      - run:
           job: scrapeItem
           params:
             url: urlToScrape
  scrapeItem:
    steps:
      - goto: 
          url: url
      - many:
           ...
```
