### ISSUE TITLE
Storing PDF and screenshots accept a flag for custom storage path

### ISSUE THREAD

**Issue by joseconstela** [joseconstela/webparsy#25]
Accept the following schema to specify the path of a PDF and screenshot, instead of using a hardcoded value:

```yml
version: 1
jobs:
  main:
    steps:
      - goto: 
          url: http://example.com
      - screenshot:
          path: 
            flag: screenshotLocation
```
